### ISSUE TITLE
Getting dict after applying `gate_sample`

### ISSUE THREAD

**Issue by asmvernon** [whitews/FlowKit#28]
Hi Scott, 
I've been following your [tutorial](https://github.com/whitews/FlowKit/blob/master/examples/flowkit-tutorial.ipynb) and came across an issue with getting the gating results (input 48 onward). 

The method `gate_sample` of your `GatingStrategy` class is returning a dictionary, rather than an object from the `GatingResults` class. 

`> gs_results = g_strat.gate_sample(sample)`
`> type(gs_results)`
```
dict
```
`> gs_results`
```                                                                                                                                                                                             
{'Range1': array([False, False, False, ..., False, False, False]),
 'Rectangle1': array([False, False, False, ..., False, False, False]),
 'Rectangle2': array([False, False, False, ..., False, False, False]),
 'Range2': array([False, False, False, ..., False, False, False]),
 'RatRange1': array([ True, False,  True, ..., False,  True, False]),
 'RatRange2': array([False, False,  True, ..., False, False, False]),
 'RatRange1a': array([False, False,  True, ..., False, False, False]),
[...]
```

I've tried calling `GatingResults` using the`gs_results`  output (I copy-pasted your source as I was unable to import it), but I haven't succeeded:

```
GatingResults(gs_results, sample_id=sample.original_filename)                                                                                                                                               

AttributeError                            Traceback (most recent call last)
<ipython-input-17-e88b290ac31f> in <module>
----> 1 GatingResults(gs_results_dict, sample.original_filename)

<ipython-input-3-fd1b25407c76> in __init__(self, results_dict, sample_id)
      4         self.report = None
      5         self.sample_id = sample_id
----> 6         self._process_results()
      7 
      8     @staticmethod

<ipython-input-3-fd1b25407c76> in _process_results(self)
     25             if 'events' not in res:
     26                 # it's a quad gate with sub-gates
---> 27                 for sub_g_id, sub_res in res.items():
     28                     pd_dict = self._get_pd_result_dict(sub_res, sub_g_id)
     29                     pd_dict['quadrant_parent'] = g_id

AttributeError: 'numpy.ndarray' object has no attribute 'items'

```

I'm on Ubuntu bionic (18.04) and Python 3.6.8

**Comment by whitews** [comment]
Hi Andrea,

Thanks for submitting the issue, I'll have a look today. What version of FlowKit are you using, the one from PyPI (via pip) or the current version directly from git?

**Comment by asmvernon** [comment]
PyPI's version

**Comment by whitews** [comment]
Ahh, the GatingResults class was added after the 0.1.0 release (back in February). After that release I created the 0.2.0 milestone that I thought would be done in a few months, but got side-tracked by another project. I am now back to working on FlowKit regularly and the 0.2.0 release is scheduled for Oct. 31st.

I don't want to release another version now as some of the new features are not fully baked. However, I do try to avoid committing broken code, and regularly use the latest git version myself, so it is relatively safe to install from git. You can install the latest version using pip using:

pip install git+https://github.com/whitews/flowkit

Also, note the GatingResults class is not intended to be imported directly. The idea being that there shouldn't be any reason a user would need to create an instance of that class, the results should be generated by the package.

Finally, if you have any features you'd like to see in FlowKit, check the list of issues and if it's not there feel free to submit new ones.

**Comment by asmvernon** [comment]
Ok, thanks for the info. And yeah, I only tried to import GatingResults directly to see if that fixed the bug :)

Will look into suggesting new features :)
Thanks again!
